@Library('ToolsPipelineLib') _


pipeline {
    stages {
        stage('Get version') {
            steps {
                container('jnlp') {
                    dir ("${env.WORKSPACE}") {
                        sh "ls -lrta ."
                        sh "sed -n -e 's/^.*project\\(.*\\)/\\1/p' vpux_emulator/CMakeLists.txt"
                        sh "sed -n -e 's/^.*project(vpux_emulator.*VERSION *\\(.*\\))/\\1/p' vpux_emulator/CMakeLists.txt"
                        sh "echo BUILD_VERSION = ${env.BUILD_VERSION};"
                    }
                }
            }
        }
    }
}
