@Library('ToolsPipelineLib') _


pipeline {
    agent {
        kubernetes (
            cloud: 'kubi-linux',
            inheritFrom: 'default',
            containerTemplates: [
                containerTemplate(
                    name: 'openvino',
                    image: 'ger-registry.caas.intel.com/movitools/nntools:openvino_1.8',
                    command: 'cat',
                    resourceRequestCpu: '8',
                    resourceLimitCpu: '8',
                    resourceLimitMemory: '32Gi',
                    ttyEnabled: true
                )
            ]
        )
    }
    environment {
        AF_TOKEN = credentials("CID-sys_mtbuild-af01p_ir-key_text")
        PYTHONUNBUFFERED = 1
        ARTIFACTORY_URL = "https://af01p-ir.devtools.intel.com/artifactory"
        ARTIFACTORY_KEY = credentials("CID-sys_mtbuild-af01p_ir-key_text")
        SSH_KEY = credentials("CID-1Source-SSH-Test")
        JFROG_CLI_OFFER_CONFIG = false
    }
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '14', numToKeepStr: '14')
        disableConcurrentBuilds()
        timeout(time: 12, unit: 'HOURS')
        durabilityHint 'PERFORMANCE_OPTIMIZED'
        copyArtifactPermission('*')
        checkoutToSubdirectory('vpux_emulator')
        parallelsAlwaysFailFast()
    }
    stages {
        stage('Get version') {
            steps {
                container('jnlp') {
                    dir ("${env.WORKSPACE}") {
                        sh "env"
                        sh "env | grep ARTIFACTORY_KEY > ARTIFACTORY_KEY.txt"
                        sh "env | grep SSH_KEY > SSH_KEY.txt"
                        sh "git init ."
                        sh "git --version"
                        sh "git clone git@github.com:SeptimiuIoachimNeagaIntel/JenkinsTest.git" 
                        sh "ls -lrta"
                    }
                }
            }
            post {
                success {
                    archiveArtifacts "Package/**/*"
                }
            }
        }
    }
}
