@Library('ToolsPipelineLib') _


pipeline {
    agent {
        kubernetes (
            cloud: 'kubi-linux',
            inheritFrom: 'default',
            containerTemplates: [
                containerTemplate(
                    name: 'openvino',
                    image: 'ger-registry.caas.intel.com/movitools/nntools:openvino_1.8',
                    command: 'cat',
                    resourceRequestCpu: '8',
                    resourceLimitCpu: '8',
                    resourceLimitMemory: '32Gi',
                    ttyEnabled: true
                )
            ]
        )
    }
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '14', numToKeepStr: '14')
        disableConcurrentBuilds()
        timeout(time: 12, unit: 'HOURS')
        durabilityHint 'PERFORMANCE_OPTIMIZED'
        copyArtifactPermission('*')
        checkoutToSubdirectory('vpux_emulator')
        parallelsAlwaysFailFast()
    }
    stages {
        stage('Get version') {
            steps {
                container('jnlp') {
                    dir ("${env.WORKSPACE}") {
                        sh "ls -lrta"
                    }
                }
            }
        }
    }
}
